# 독립 실행용 프로필 (Eureka 없이 실행)
spring:
  profiles: standalone

# Eureka 비활성화
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

# 로깅 레벨 증가 (개발용)
logging:
  level:
    com.ecommerce.msa.user: DEBUG
    org.springframework.web: DEBUG

# 개발용 데이터베이스 (H2 사용 시)
# spring:
#   datasource:
#     url: jdbc:h2:mem:userdb
#     driver-class-name: org.h2.Driver
#     username: sa
#     password: 
#   h2:
#     console:
#       enabled: true
