server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:eureka-server}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA:false}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:false}
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: ${EUREKA_SELF_PRESERVATION:false}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,metrics}
  endpoint:
    health:
      show-details: ${MANAGEMENT_HEALTH_SHOW_DETAILS:always}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.netflix.eureka: ${LOGGING_LEVEL_COM_NETFLIX_EUREKA:INFO}
    com.netflix.discovery: ${LOGGING_LEVEL_COM_NETFLIX_DISCOVERY:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
